package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/quantumx-apps/go-office/internal/assetfetch"
)

func main() {
	out := flag.String("out", "", "output Go file path (default: pkg/office/assets_version.go)")
	versionFile := flag.String("version-file", "", "path to scripts/euro-office.version")
	flag.Parse()

	root, err := assetfetch.FindRepoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	vf := *versionFile
	if vf == "" {
		vf = filepath.Join(root, "scripts", "euro-office.version")
	}
	ver, err := assetfetch.LoadVersion(vf)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-assets-version:", err)
		os.Exit(1)
	}

	outPath := *out
	if outPath == "" {
		outPath = filepath.Join(root, "pkg", "office", "assets_version.go")
	}

	content := fmt.Sprintf(`// Code generated by cmd/gen-assets-version; DO NOT EDIT.

package office

// ExpectedAssetsVersion is the Euro-Office Document Server release pinned by this go-office build.
const ExpectedAssetsVersion = %q
`, ver)

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gen-assets-version:", err)
		os.Exit(1)
	}

	if !strings.HasSuffix(outPath, "assets_version.go") {
		fmt.Println("wrote", outPath)
	}
}
