// Code generated by cmd/gen-assets-version; DO NOT EDIT.

package office

// ExpectedAssetsVersion is the Euro-Office Document Server release pinned by this go-office build.
const ExpectedAssetsVersion = "9.3.4-hotfix.1"
