name: regular tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
      - run: make test

  lint:
    name: golangci-lint
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: make lint
